# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agentshield < Formula
  desc "Local-first runtime security gateway for LLM agents"
  homepage "https://github.com/gzhole/AI-Agentic-Shield"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gzhole/AI-Agentic-Shield/releases/download/v0.1.0/agentshield_0.1.0_darwin_amd64.tar.gz"
      sha256 "d64dcc31d2eea273fe0dab5d74539578185bf05440372d3d6f0e1ad3259619fe"

      def install
        bin.install "agentshield"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gzhole/LLM-Agentic-Shield/releases/download/v0.1.0/agentshield_0.1.0_darwin_arm64.tar.gz"
      sha256 "7180c041de45de7a65bc3afb88d1624e52a9ae7868e1297be370f486c65e8455"

      def install
        bin.install "agentshield"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gzhole/LLM-Agentic-Shield/releases/download/v0.1.0/agentshield_0.1.0_linux_amd64.tar.gz"
      sha256 "69567f22c12d76b5a9d486ef22cd8dce90c41a1b863cde071f4c3fc41d5906fc"
      def install
        bin.install "agentshield"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gzhole/LLM-Agentic-Shield/releases/download/v0.1.0/agentshield_0.1.0_linux_arm64.tar.gz"
      sha256 "6a2d7a42569d9ff53d0de345dfb81ea9ad6a3793df093b58e8312218a74c24de"
      def install
        bin.install "agentshield"
      end
    end
  end

  test do
    system "#{bin}/agentshield", "version"
  end
end
