# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agentshield < Formula
  desc "Local-first runtime security gateway for LLM agents"
  homepage "https://github.com/gzhole/AI-Agentic-Shield"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gzhole/AI-Agentic-Shield/releases/download/v0.1.0/agentshield_0.1.0_darwin_amd64.tar.gz"
      sha256 "b600067996ac8957bde7edf3141ccc7276bc3eda0fb5b5bd7420453d801341d0"

      def install
        bin.install "agentshield"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gzhole/AI-Agentic-Shield/releases/download/v0.1.0/agentshield_0.1.0_darwin_arm64.tar.gz"
      sha256 "411e56fa60260066d3c785829c0a835c219e4f2cb4ffcd151c51264bd4ed5254"

      def install
        bin.install "agentshield"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gzhole/AI-Agentic-Shield/releases/download/v0.1.0/agentshield_0.1.0_linux_amd64.tar.gz"
      sha256 "ed8d8e2bf5a10d9a6c22347394205cc978dd4d5e1828088c01abe4e38847a43d"
      def install
        bin.install "agentshield"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gzhole/AI-Agentic-Shield/releases/download/v0.1.0/agentshield_0.1.0_linux_arm64.tar.gz"
      sha256 "781ade908083ae41364305ad5e1e14962c3b4c3b5f917d2909f7398a2b03fc79"
      def install
        bin.install "agentshield"
      end
    end
  end

  test do
    system "#{bin}/agentshield", "version"
  end
end
