# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agentshield < Formula
  desc "Local-first runtime security gateway for AI agents"
  homepage "https://github.com/gzhole/Agentic-gateway"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gzhole/Agentic-gateway/releases/download/v0.1.0/agentshield_0.1.0_darwin_amd64.tar.gz"
      sha256 "ab2b14632e5354199c670a71f60b9080d4a46e6453d589e688dfe2aeb28a2204"

      def install
        bin.install "agentshield"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gzhole/Agentic-gateway/releases/download/v0.1.0/agentshield_0.1.0_darwin_arm64.tar.gz"
      sha256 "d3a8ffcdfee84ebbf25edcbcfdf82e51bd8af7274bba73eac99a105134e360e1"

      def install
        bin.install "agentshield"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gzhole/Agentic-gateway/releases/download/v0.1.0/agentshield_0.1.0_linux_amd64.tar.gz"
      sha256 "15bcaac098fc6a0a7159c834c9f817036745bdf9e4c8fff8734bc4d61c73d61a"
      def install
        bin.install "agentshield"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gzhole/Agentic-gateway/releases/download/v0.1.0/agentshield_0.1.0_linux_arm64.tar.gz"
      sha256 "9316085559ae7daf19a4cd355545c0e5f246f784ff0b4df38538fb7407d5ffa4"
      def install
        bin.install "agentshield"
      end
    end
  end

  test do
    system "#{bin}/agentshield", "version"
  end
end
